db:
  host: "postgres"
  user: "citizix_user"
  password: "S3cret"
  dbname: "citizix_db"
  port: 5432

kafka:
  brokers:
    - "kafka-0:29092"
    - "kafka-1:29092"
    - "kafka-2:29092"
  topic: "topic0"
  partition: 3

nats:
  url: "nats://nats:4222, nats://nats1:4222, nats://nats2:4222"
  subject: "subject0"