db:
  host: "postgres"
  user: "citizix_user"
  password: "S3cret"
  dbname: "citizix_db"
  port: 5432

kafka:
  brokers:
    - "kafka-0:29092"
    - "kafka-1:29092"
    - "kafka-2:29092"
  topic: "topic0"
  partition: 3


kafka3:
  brokers:
    - "kafka-0:29092"
    - "kafka-1:29092"
    - "kafka-2:29092"
  topics:
    - "topic1"
    - "topic2"
    - "topic3"
  partition: 1

nats:
  url: "nats://nats:4222, nats://nats1:4222, nats://nats2:4222"
  subject: "subject0"
  
  
nats3:
  url: "nats://nats:4222, nats://nats1:4222, nats://nats2:4222"
  subjects:
    - "subject1"
    - "subject2"
    - "subject3"