version: '3'
services:
  kafka-0:
    image: confluentinc/cp-kafka
    networks:
      - default
    container_name: kafka-0
    hostname: kafka-0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka-0:29092,CONTROLLER://kafka-0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-0:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka-0:29093,1@kafka-1:29093,2@kafka-2:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    deploy:
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB
  
  kafka-1:
    image: confluentinc/cp-kafka
    networks:
      - default
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka-1:29092,CONTROLLER://kafka-1:29093,EXTERNAL://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-1:29092,EXTERNAL://localhost:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka-0:29093,1@kafka-1:29093,2@kafka-2:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    deploy:
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB
  
  kafka-2:
    image: confluentinc/cp-kafka
    networks:
      - default
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka-2:29092,CONTROLLER://kafka-2:29093,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-2:29092,EXTERNAL://localhost:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka-0:29093,1@kafka-1:29093,2@kafka-2:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    deploy:
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB
          
#            - "--name=nats1"
#            - "--http_port=8222"
#            - "-cluster nats://0.0.0.0:6222"
#            - "--js"
#            - "--sd=/data"
          
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      - default
    command:
      - "--name=nats1"
      - "--cluster_name=c1"
      - "--cluster=nats://nats:6222"
      - "--routes=nats-route://nats:6222,nats-route://nats1:6222,nats-route://nats2:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    deploy:
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB
  nats1:
    image: nats
    ports:
      - "4223:4222"
    command:
      - "--name=nats2"
      - "--cluster_name=c1"
      - "--cluster=nats://nats1:6222"
      - "--routes=nats-route://nats:6222,nats-route://nats1:6222,nats-route://nats2:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    networks:
      - default
    depends_on: [ "nats" ]
    deploy:
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB
          
  nats2:
    image: nats
    ports:
      - "4224:4222"
    command:
      - "--name=nats3"
      - "--cluster_name=c1"
      - "--cluster=nats://nats2:6222"
      - "--routes=nats-route://nats:6222,nats-route://nats1:6222,nats-route://nats2:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    networks:
      - default
    depends_on: [ "nats" ]
    deploy:
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB
          
          
          
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - poc-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    networks:
      - default
  
  kafka-consumer:
    build: .
    command:
      "./main consume3Kafka"
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
      - postgres
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB

          
  nat-consumer:
    build: .
    command:
      "./main consume3Nats"
    depends_on:
      - nats
      - postgres
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1.0"         # CPU limit: 1 CPU core
          memory: 500M        # Memory limit: 500MB
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:29092, kafka-1:29092, kafka-2:29092
    ports:
      - 8080:8080
      
      
      
      
volumes:
  nats:
  nats1:
  nats2:
  poc-postgresql:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local

networks:
    default:
        driver: bridge